[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Fallback for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  autoLaunch = true
  framework = "vite"
  # Disable automatic installation of extensions
  autoInstall = false
  node_bundler = "esbuild"
  
# Environment variables will be set in Netlify dashboard

# -------------------------------------------------------------------
# Scheduled Functions
# Daily keepalive ping so Supabase project never idles (runs 06:00 UTC)
# Adjust cron as needed (cron format: min hour day month weekday)
# -------------------------------------------------------------------
[[scheduled.functions]]
  name = "keepalive"
  cron = "0 6 * * *"